# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{spree_static_content}
  s.version = "0.30.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Peter Berkenbosch", "Roman Smirnov"]
  s.date = %q{2010-12-03}
  s.description = %q{Extention to manage the static pages for your Spree shop.}
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    ".gitignore",
     "CONTRIBUTORS.textile",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "app/controllers/admin/pages_controller.rb",
     "app/controllers/spree/base_controller_decorator.rb",
     "app/controllers/static_content_controller.rb",
     "app/models/page.rb",
     "app/views/admin/pages/_form.html.erb",
     "app/views/admin/pages/edit.html.erb",
     "app/views/admin/pages/index.html.erb",
     "app/views/admin/pages/new.html.erb",
     "app/views/static_content/show.html.erb",
     "config/locales/en-GB.yml",
     "config/locales/en.yml",
     "config/locales/es-ES.yml",
     "config/locales/nl-BE.yml",
     "config/locales/nl-NL.yml",
     "config/locales/pl.yml",
     "config/locales/pt-BR.yml",
     "config/locales/ru-RU.yml",
     "config/routes.rb",
     "lib/generators/spree_static_content/install_generator.rb",
     "lib/generators/templates/db/migrate/20081216193152_create_pages.rb",
     "lib/generators/templates/db/migrate/20090625125735_extend_pages.rb",
     "lib/generators/templates/db/migrate/20090814113100_add_visible_to_pages.rb",
     "lib/generators/templates/db/migrate/20090814142845_add_default_true_to_visible_for_page.rb",
     "lib/generators/templates/db/migrate/20090829000527_add_index_for_page.rb",
     "lib/generators/templates/db/migrate/20091219021134_add_meta_fields_to_pages.rb",
     "lib/generators/templates/db/migrate/20100204105222_add_layout_to_pages.rb",
     "lib/generators/templates/db/migrate/20100323085528_add_show_in_sidebar_option_to_pages.rb",
     "lib/generators/templates/public/javascripts/wymeditor/iframe/default/lbl-blockquote.png",
     "lib/generators/templates/public/javascripts/wymeditor/iframe/default/lbl-h1.png",
     "lib/generators/templates/public/javascripts/wymeditor/iframe/default/lbl-h2.png",
     "lib/generators/templates/public/javascripts/wymeditor/iframe/default/lbl-h3.png",
     "lib/generators/templates/public/javascripts/wymeditor/iframe/default/lbl-h4.png",
     "lib/generators/templates/public/javascripts/wymeditor/iframe/default/lbl-h5.png",
     "lib/generators/templates/public/javascripts/wymeditor/iframe/default/lbl-h6.png",
     "lib/generators/templates/public/javascripts/wymeditor/iframe/default/lbl-p.png",
     "lib/generators/templates/public/javascripts/wymeditor/iframe/default/lbl-pre.png",
     "lib/generators/templates/public/javascripts/wymeditor/iframe/default/wymiframe.css",
     "lib/generators/templates/public/javascripts/wymeditor/iframe/default/wymiframe.html",
     "lib/generators/templates/public/javascripts/wymeditor/jquery.wymeditor.js",
     "lib/generators/templates/public/javascripts/wymeditor/jquery.wymeditor.pack.js",
     "lib/generators/templates/public/javascripts/wymeditor/lang/ca.js",
     "lib/generators/templates/public/javascripts/wymeditor/lang/cs.js",
     "lib/generators/templates/public/javascripts/wymeditor/lang/de.js",
     "lib/generators/templates/public/javascripts/wymeditor/lang/en.js",
     "lib/generators/templates/public/javascripts/wymeditor/lang/es.js",
     "lib/generators/templates/public/javascripts/wymeditor/lang/fa.js",
     "lib/generators/templates/public/javascripts/wymeditor/lang/fr.js",
     "lib/generators/templates/public/javascripts/wymeditor/lang/he.js",
     "lib/generators/templates/public/javascripts/wymeditor/lang/hu.js",
     "lib/generators/templates/public/javascripts/wymeditor/lang/it.js",
     "lib/generators/templates/public/javascripts/wymeditor/lang/nb.js",
     "lib/generators/templates/public/javascripts/wymeditor/lang/nl.js",
     "lib/generators/templates/public/javascripts/wymeditor/lang/nn.js",
     "lib/generators/templates/public/javascripts/wymeditor/lang/pl.js",
     "lib/generators/templates/public/javascripts/wymeditor/lang/pt-br.js",
     "lib/generators/templates/public/javascripts/wymeditor/lang/pt.js",
     "lib/generators/templates/public/javascripts/wymeditor/lang/ru.js",
     "lib/generators/templates/public/javascripts/wymeditor/lang/sv.js",
     "lib/generators/templates/public/javascripts/wymeditor/lang/tr.js",
     "lib/generators/templates/public/javascripts/wymeditor/lang/zh_cn.js",
     "lib/generators/templates/public/javascripts/wymeditor/plugins/hovertools/jquery.wymeditor.hovertools.js",
     "lib/generators/templates/public/javascripts/wymeditor/plugins/resizable/jquery.wymeditor.resizable.js",
     "lib/generators/templates/public/javascripts/wymeditor/plugins/resizable/readme.txt",
     "lib/generators/templates/public/javascripts/wymeditor/plugins/tidy/README",
     "lib/generators/templates/public/javascripts/wymeditor/plugins/tidy/jquery.wymeditor.tidy.js",
     "lib/generators/templates/public/javascripts/wymeditor/plugins/tidy/tidy.php",
     "lib/generators/templates/public/javascripts/wymeditor/plugins/tidy/wand.png",
     "lib/generators/templates/public/javascripts/wymeditor/skins/default/icons.png",
     "lib/generators/templates/public/javascripts/wymeditor/skins/default/skin.css",
     "lib/generators/templates/public/javascripts/wymeditor/skins/default/skin.js",
     "lib/generators/templates/public/javascripts/wymeditor/skins/minimal/images/bg.header.gif",
     "lib/generators/templates/public/javascripts/wymeditor/skins/minimal/images/bg.selector.silver.gif",
     "lib/generators/templates/public/javascripts/wymeditor/skins/minimal/images/bg.wymeditor.png",
     "lib/generators/templates/public/javascripts/wymeditor/skins/minimal/images/icons.silver.gif",
     "lib/generators/templates/public/javascripts/wymeditor/skins/minimal/skin.css",
     "lib/generators/templates/public/javascripts/wymeditor/skins/minimal/skin.js",
     "lib/generators/templates/public/javascripts/wymeditor/skins/silver/COPYING",
     "lib/generators/templates/public/javascripts/wymeditor/skins/silver/README",
     "lib/generators/templates/public/javascripts/wymeditor/skins/silver/images/bg.header.gif",
     "lib/generators/templates/public/javascripts/wymeditor/skins/silver/images/bg.selector.silver.gif",
     "lib/generators/templates/public/javascripts/wymeditor/skins/silver/images/bg.wymeditor.png",
     "lib/generators/templates/public/javascripts/wymeditor/skins/silver/images/icons.silver.gif",
     "lib/generators/templates/public/javascripts/wymeditor/skins/silver/skin.css",
     "lib/generators/templates/public/javascripts/wymeditor/skins/silver/skin.js",
     "lib/generators/templates/public/javascripts/wymeditor/skins/twopanels/icons.png",
     "lib/generators/templates/public/javascripts/wymeditor/skins/twopanels/skin.css",
     "lib/generators/templates/public/javascripts/wymeditor/skins/twopanels/skin.js",
     "lib/generators/templates/public/javascripts/wymeditor/skins/wymeditor_icon.png",
     "lib/generators/templates/public/stylesheets/static.css",
     "lib/spree_static_content.rb",
     "lib/spree_static_content_hooks.rb",
     "spec/controllers/admin/pages_controller_spec.rb",
     "spec/controllers/content_controller_spec.rb",
     "spec/models/page_spec.rb",
     "spec/spec.opts",
     "spec/spec_helper.rb",
     "spree_static_content.gemspec"
  ]
  s.homepage = %q{http://github.com/spree/spree-static-content}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{Extention to manage the static pages for your Spree shop.}
  s.test_files = [
    "spec/models/page_spec.rb",
     "spec/spec_helper.rb",
     "spec/controllers/content_controller_spec.rb",
     "spec/controllers/admin/pages_controller_spec.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<spree_core>, [">= 0.30.0.beta1"])
    else
      s.add_dependency(%q<spree_core>, [">= 0.30.0.beta1"])
    end
  else
    s.add_dependency(%q<spree_core>, [">= 0.30.0.beta1"])
  end
end

